### ISSUE TITLE
Mejoras evaluación intermedia

### ISSUE THREAD

**Issue by pixelmary** [Adalab/evaluacion-intermedia-modulo-2-martacruces#1]
Marta te digo los fallos que has tenido. Te ha faltado guardar en una variable tu número aleatorio generado para que lo tengas al iniciar la aplicación fuera de la función del click, luego llamas en el load de la ventana a la variable generada en lugar de a la función.
Para comparar necesitas usar la triple igualdad en el caso de has ganado campeona, un único signo = asigna un valor, un triple signo === compara. A parte te ha faltado el contador. En general creo que no vas por mal camino y llegarás bien a la evaluación final.

## Javascript

 - En la carga de la página, ejecuta la función 'getRandomNumber' y almacene el valor devuelto en una constante para trabajar con él más adelante.  
 - Si llamas a la función 'getRandomNumer' dentro de la función manejadora del evento creará un nuevo número aleatorio cada vez que el usuario haga clic en el botón. Eso hace que el juego sea complejo y las pistas no tendrán sentido.
 - Generemos el número aleatorio cuando se carga la página.
 - Definir la lógica (función) para hacer que el contador funcione
 - Recuerda convertir el string a number
 - Extraer el pintor de comentarios a una función
 - Arregla la estructura del if: verifica una opción, luego la otra y
   luego el resto es suficiente con una instrucción else
 - Recuerda que cada vez que usamos .innerHTML o .value para obtener contenido DOM, recibimos un string. A veces tendremos que usar parseInt () para convertirlo en un número.  

## Avanzado

 - Mueve la lógica de retroalimentación a una función y ejecútala en
   cada clic
 - Mueve la lógica del contador a una función y ejecútala con cada clic.
 - Estás escribiendo muchas veces "elem.innerHTML = 'something';",
   ¿qué hay de hacer una función que acepte un string como parámetro y
   la pinte en 'elem'?

## JavaScript buenas prácticas

 - Usa === en lugar de = para las comparaciones  

## Buenas practicas generales

 - Indenta y evita espacios en blanco adicionales para mejorar la
   legibilidad y evitar errores
 - Intenta mejorar tus mensajes de commit. "Agregar JS" es un poco pobre. "Agregar lógica de número aleatorio" es más explicativo. 
 
## CSS
  - Evita agregar estilos hasta que el código js sea sólido como una roca. 
  
  ----------------
**Estás cerca de la solución del ejercicio, pero aquí tienes una guía de pasos para completarlo de todos modos ;)**
   
 - Guardar una referencia a elementos DOM en variables 
 - Genera el número aleatorio y guárdalo en una variable. 
 - Iniciar el contador de ensayos a 0
 - Define una función que se ejecuta cuando el usuario hace clic en el
   botón, que incrementa el contador y pinta su valor en el HTML.
 - Recopila el valor de la entrada HTML y compáralo con el número
   aleatorio si son iguales, dibuja un mensaje 'Tú ganas' si es
   inferior, dibuje un mensaje 'Demasiado corto' si es más alto, dibuje
   un mensaje 'Demasiado largo' 
 - Asigna un listener al botón de clic para ejecutar la función anterior 

   Avísame si tienes dudas;)
   
   ¡¡A por ello!!

**Comment by martacruces** [comment]
Hola, María, he terminado de hacer el ejercicio con la revisión que me has hecho.
Muchas gracias!
